-- Create projects table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  image text,
  technologies text[] not null,
  live_url text,
  github_url text,
  size text -- 'large', 'medium', 'small'
);

-- Create experience table
create table public.experience (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  company text not null,
  location text not null,
  start_date text not null,
  end_date text not null,
  description text not null,
  technologies text[] not null
);

-- Create skills table
create table public.skills (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  category text not null, -- 'Frontend Development', 'Backend Development', 'Tools & DevOps'
  name text not null,
  level text not null, -- 'Expert', 'Advanced', 'Intermediate'
  years text not null -- '3y+', '2y+'
);

-- Set up Row Level Security (RLS)
alter table public.projects enable row level security;
alter table public.experience enable row level security;
alter table public.skills enable row level security;

-- Create policies
create policy "Public projects are viewable by everyone" on public.projects for select using (true);
create policy "Public experience are viewable by everyone" on public.experience for select using (true);
create policy "Public skills are viewable by everyone" on public.skills for select using (true);

-- Authenticated policies (omitted for brevity but implied same as before)
create policy "Enable insert for authenticated users only" on public.projects for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.projects for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.projects for delete using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users only" on public.experience for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.experience for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.experience for delete using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users only" on public.skills for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.skills for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.skills for delete using (auth.role() = 'authenticated');
