-- Create testimonials table
create table public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text not null,
  company text,
  content text not null,
  avatar_url text,
  rating integer check (rating >= 1 and rating <= 5)
);

-- Set up Row Level Security (RLS)
alter table public.testimonials enable row level security;

-- Create policies
create policy "Public testimonials are viewable by everyone" on public.testimonials for select using (true);
create policy "Enable insert for authenticated users only" on public.testimonials for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.testimonials for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.testimonials for delete using (auth.role() = 'authenticated');
