-- Create experience table (if not exists) and enable RLS
create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  company text not null,
  location text not null,
  start_date text not null,
  end_date text not null,
  description text not null,
  technologies text[] default '{}'
);

alter table public.experience enable row level security;

create policy "Public experience is viewable by everyone" on public.experience for select using (true);
create policy "Enable insert for authenticated users only" on public.experience for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.experience for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.experience for delete using (auth.role() = 'authenticated');
